[package]
name = "hello-web"
version = "0.1.0"
authors = ["Andrew Radev <andrey.radev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gotham = "0.4"
gotham_derive = "0.4"
askama = "0.8"
hyper = "0.12"
mime = "0.3"
time = "0.2"
serde = { version = "1.0", features = ["derive"] }

actix-web = "3.3.2"
actix-rt = "1.1.1"
http = "0.2.3"
